language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

before_install:
  - "cpanm --verbose Module::Install Module::Install::CPANfile"
  - ./dev-bin/travis-prepare.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

